name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
     steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Build & Push image
      run: |
        docker login -u ${{ secrets.apatel211 }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker build -t apatel211/cypress1:latest 
        docker push apatel211/cypress1:latest
